all: mainPrgm.c ../HeaderFiles/maths.h
	gcc -o m1 mainPrgm.c ../HeaderFiles/stackLib.a 

rm:
	rm *.o
temp:
	gcc -o m1 mainPrgm.c ../HeaderFiles/add.o ../HeaderFiles/sub.o ../HeaderFiles/mult.o ../HeaderFiles/div.o ../HeaderFiles/square.o ../HeaderFiles/stackFuncs.o -o all
